name: CI

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: simonouyangbcgdv/s3-sync-action
        path: s3-sync-action
    - name: Run a one-line script
      run: echo Hello, world, dear, my branch!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
